-- These are all the props that are spawnable via /prop

PropConfig = {
	{categoryName = "Roadworks", description = "Road signs used for public works related roleplay", components = {
		{name = "Flagger Paddle", spawn = "prop_flagger_sign_01"},
		{name = "Large Striped Cone", spawn ="prop_roadcone01a" },
		{name = "Large Cone", spawn ="prop_roadcone01c" },
		{name = "Medium Striped Cone", spawn ="prop_roadcone02a" },
		{name = "Medium Cone", spawn ="prop_roadcone02c" },
		{name = "Delineator", spawn ="prop_mp_cone_04" },
		{name = "Road Work Flag", spawn ="prop_consign_flag_01" },
		{name = "Work Crew Flag", spawn ="prop_consign_flag_21" },
		{name = "Utility Work Flag", spawn ="prop_consign_flag_18" },
		{name = "Shoulder Work Flag", spawn ="prop_consign_flag_19" },
		{name = "Right Lane Closed Flag", spawn ="prop_consign_flag_02" },
		{name = "Left Lane Closed Flag", spawn ="prop_consign_flag_03" },
		{name = "Right Lane Ends Flag", spawn ="prop_consign_flag_04" },
		{name = "Left Lane Ends Flag", spawn ="prop_consign_flag_05" },
		{name = "Keep Left Flag", spawn ="prop_consign_flag_13" },
		{name = "Keep Right Flag", spawn ="prop_consign_flag_14" },
		{name = "Flagger Ahead Flag", spawn ="prop_consign_flag_08" },
		{name = "Flagger Symbol Flag", spawn ="prop_consign_flag_06" },
		{name = "Prepare to Stop Flag", spawn ="prop_consign_flag_07" },
		{name = "Road Closed Ahead Flag", spawn ="prop_consign_flag_10" },
		{name = "Road Closed Flag", spawn ="prop_consign_flag_09" },
		{name = "Detour Ahead Flag", spawn ="prop_consign_flag_25" },
		{name = "Detour Left/Right Flag", spawn ="prop_consign_flag_26" },
		{name = "Detour Left Flag", spawn ="prop_consign_flag_27" },
		{name = "Detour Right Flag", spawn ="prop_consign_flag_28" },
		{name = "Detour Straight Flag", spawn ="prop_consign_flag_29" },
		{name = "Traffic Incident Flag", spawn ="prop_consign_flag_11" },
		{name = "Emergency Scene Flag", spawn ="prop_consign_flag_22" },
		{name = "Road Flooded Flag", spawn ="prop_consign_flag_15" },
		{name = "Fire Activity Flag", spawn ="prop_consign_flag_16" },
		{name = "Tow Truck Flag", spawn ="prop_consign_flag_17" },
		{name = "Check Point Flag", spawn ="prop_consign_flag_12" },
		{name = "Pilot Car Flag", spawn ="prop_consign_flag_23" },
		{name = "Fines Doubled Flag", spawn ="prop_consign_flag_24" },
		{name = "Mower Ahead Flag", spawn ="prop_consign_flag_20" },
		{name = "Slow Flag", spawn ="prop_consign_flag_30" },
		{name = "Stop Flag", spawn ="prop_consign_flag_stop" },
		{name = "custom Flag", spawn ="prop_consign_flag_custom" },
		{name = "Road Work Barrier", spawn ="prop_barrier_sign_01" },
		{name = "Work Crew Barrier", spawn ="prop_barrier_sign_21" },
		{name = "Utility Work Barrier", spawn ="prop_barrier_sign_18" },
		{name = "Shoulder Work Barrier", spawn ="prop_barrier_sign_19" },
		{name = "Right Lane Closed Barrier", spawn ="prop_barrier_sign_02" },
		{name = "Left Lane Closed Barrier", spawn ="prop_barrier_sign_03" },
		{name = "Right Lane Ends Barrier", spawn ="prop_barrier_sign_04" },
		{name = "Left Lane Ends Barrier", spawn ="prop_barrier_sign_05" },
		{name = "Keep Left Barrier", spawn ="prop_barrier_sign_13" },
		{name = "Keep Right Barrier", spawn ="prop_barrier_sign_14" }, 
		{name = "Flagger Ahead Barrier", spawn ="prop_barrier_sign_08" },
		{name = "Flagger Symbol Barrier", spawn ="prop_barrier_sign_06" },
		{name = "Prepare to Stop Barrier", spawn ="prop_barrier_sign_07" },
		{name = "Road Closed Ahead Barrier", spawn ="prop_barrier_sign_10" },
		{name = "Road Closed Barrier", spawn ="prop_barrier_sign_09" },
		{name = "Detour Ahead Barrier", spawn ="prop_barrier_sign_25" },
		{name = "Detour Arrow Barricade", spawn ="prop_barrier_sign_detour" },
		{name = "Detour Left/Right Barrier", spawn ="prop_barrier_sign_26" },
		{name = "Detour Left Barrier", spawn ="prop_barrier_sign_27" },
		{name = "Detour Right Barrier", spawn ="prop_barrier_sign_28" },
		{name = "Detour Straight Barrier", spawn ="prop_barrier_sign_29" },
		{name = "Traffic Incident Barrier", spawn ="prop_barrier_sign_11" },
		{name = "Emergency Scene Barrier", spawn ="prop_barrier_sign_22" },
		{name = "Road Flooded Barrier", spawn ="prop_barrier_sign_15" },
		{name = "Fire Activity Barrier", spawn ="prop_barrier_sign_16" },
		{name = "Tow Truck Barrier", spawn ="prop_barrier_sign_17" },
		{name = "Check Point Barrier", spawn ="prop_barrier_sign_12" },
		{name = "Pilot Car Barrier", spawn ="prop_barrier_sign_23" },
		{name = "Fines Doubled Barrier", spawn ="prop_barrier_sign_24" },
		{name = "Mower Ahead Barrier", spawn ="prop_barrier_sign_20" },
		{name = "Slow Barrier", spawn ="prop_barrier_sign_30" },
		{name = "Custom Barrier", spawn ="prop_barrier_sign_custom" },
		{name = "Stop Barrier", spawn ="prop_barrier_sign_stop" },
		{name = "Striped Barricade", spawn ="prop_barrier_work06a" },
		{name = "Road Work Barricade", spawn ="prop_barrier_work06b" },
		{name = "Street Closed Barricade", spawn ="prop_barrier_work06c" },
		{name = "Sidewalk Closed Barricade", spawn ="prop_barrier_work06d" },
		{name = "Road Barrel w/ Base", spawn ="prop_barrier_wat_03a" },
		{name = "Road Barrel", spawn ="prop_barrier_wat_03b" },
		{name = "Small Barricade", spawn ="prop_barrier_work01a" },
		{name = "Small Barricade w/ Light", spawn ="prop_barrier_work02a" },
		{name = "Road Work Type-III Barricade", spawn ="prop_barrier_work04a" },
		{name = "Type-III Barricade (Left)", spawn ="prop_barrier_work04b" },
		{name = "Type-III Barricade (Right)", spawn ="prop_barrier_work04br" },
		{name = "Type-III Barricade (Left w/ lights)", spawn ="prop_barrier_work04c" },
		{name = "Type-III Barricade (Right w/ lights)", spawn ="prop_barrier_work04cr" },
		{name = "Type-III Road Closed (Left)", spawn ="prop_barrier_work04dx" },
		{name = "Type-III Road Closed (Right)", spawn ="prop_barrier_work04drx" },
		{name = "Type-III Road Closed (Left w/ lights)", spawn ="prop_barrier_work04d" },
		{name = "Type-III Road Closed (Right w/ light)", spawn ="prop_barrier_work04dr" },
		{name = "Type-III Detour (Left)", spawn ="prop_barrier_work04ex" },
		{name = "Type-III Detour (Right)", spawn ="prop_barrier_work04erx" },
		{name = "Type-III Detour (Left w/ lights)", spawn ="prop_barrier_work04e" },
		{name = "Type-III Detour (Right w/ lights)", spawn ="prop_barrier_work04er" },
		{name = "Jersey Barrier", spawn ="prop_mp_conc_barrier_01" },
		{name = "Flashy Cone", spawn ="prop_flash_cone_01" },
		{name = "Free Tow Ahead", spawn ="prop_barrier_sign_31" },
		{name = "15 MPH", spawn ="prop_barrier_sign_32" },
		{name = "25 MPH", spawn ="prop_barrier_sign_33" },
		{name = "35 MPH", spawn ="prop_barrier_sign_34" },
		{name = "45 MPH", spawn ="prop_barrier_sign_35" },
		{name = "Blasting Zone", spawn ="prop_barrier_sign_36" },
		{name = "Bridge Work", spawn ="prop_barrier_sign_37" },
		{name = "Construction Entrance", spawn ="prop_barrier_sign_38" },
		{name = "End Blasting Zone", spawn ="prop_barrier_sign_39" },
		{name = "End Detour", spawn ="prop_barrier_sign_40" },
		{name = "End Road Work", spawn ="prop_barrier_sign_41" },
		{name = "Follow Pilot Car", spawn ="prop_barrier_sign_42" },
		{name = "Give Us a Brake", spawn ="prop_barrier_sign_43" },
		{name = "Hard Hat Area", spawn ="prop_barrier_sign_44" },
		{name = "Keep left", spawn ="prop_barrier_sign_45" },
		{name = "Keep Right", spawn ="prop_barrier_sign_46" },
		{name = "Litter Crew", spawn ="prop_barrier_sign_47" },
		{name = "Merge", spawn ="prop_barrier_sign_48" },
		{name = "One Lane Road", spawn ="prop_barrier_sign_49" },
		{name = "Passing Zone", spawn ="prop_barrier_sign_50" },
		{name = "Pilot Car Wait", spawn ="prop_barrier_sign_51" },
		{name = "Prisoners Working", spawn ="prop_barrier_sign_52" },
		{name = "Ramp Closed", spawn ="prop_barrier_sign_53" },
		{name = "Stay in Lane", spawn ="prop_barrier_sign_54" },
		{name = "Survey Crew", spawn ="prop_barrier_sign_55" },
		{name = "Traffic Signal", spawn ="prop_barrier_sign_56" },
		{name = "Workers", spawn ="prop_barrier_sign_57" },
		{name = "Yield", spawn ="prop_barrier_sign_58" },
	}},

	{categoryName = "Arrowboards", description = "Electronics signs displaying information", components = {
		{name = "Left Arrow Board", spawn = "prop_trafficdiv_01" },
		{name = "Right Arrow Board", spawn = "prop_trafficdiv_02" },
		{name = "Right Arrow Board 2", spawn = "prop_trafficdiv_03" },
		{name = "Caution Slow Traffic", spawn = "prop_trafficdiv_04" },
		{name = "End Detour", spawn = "prop_trafficdiv_05" },
		{name = "Detour Left", spawn = "prop_trafficdiv_06" },
		{name = "Detour Right", spawn = "prop_trafficdiv_07" },
		{name = "Detour Front", spawn = "prop_trafficdiv_08" },
		{name = "Event Parking Ahead", spawn = "prop_trafficdiv_09" },
		{name = "Flagger Ahead", spawn = "prop_trafficdiv_10" },
		{name = "Follow Detour Ahead", spawn = "prop_trafficdiv_11" },
		{name = "Left Lane Closed", spawn = "prop_trafficdiv_12" },
		{name = "Right Lane Closed", spawn = "prop_trafficdiv_13" },
		{name = "Keep Left", spawn = "prop_trafficdiv_14" },
		{name = "Keep Right", spawn = "prop_trafficdiv_15" },
		{name = "Lane Closure Ahead", spawn = "prop_trafficdiv_16" },
		{name = "Left Lane Closed 2", spawn = "prop_trafficdiv_17" },
		{name = "Pass On Shoulder", spawn = "prop_trafficdiv_18" },
		{name = "Right Lane Closed 2", spawn = "prop_trafficdiv_19" },
		{name = "Road Work Ahead", spawn = "prop_trafficdiv_20" },
		{name = "Road Works Ahead", spawn = "prop_trafficdiv_21" },
		{name = "Slown Down Ahead", spawn = "prop_trafficdiv_22" },
		{name = "Speed Ahead 30 MPH", spawn = "prop_trafficdiv_23" },
		{name = "Speed Ahead 40 MPH", spawn = "prop_trafficdiv_24" },
		{name = "Speed Ahead 50 MPH", spawn = "prop_trafficdiv_25" },
		{name = "Stopped Traffic Ahead", spawn = "prop_trafficdiv_26" },
		{name = "Work Convoy", spawn = "prop_trafficdiv_27" },
		{name = "Left Arrow Board 2", spawn = "prop_trafficdiv_28" },
	}},

	{categoryName = "Police", description = "Props used for police work, including evidence markers", components = {
    	{name = "Police Barricade", spawn = "prop_barrier_work05" },
	
		{name = "Evidence Marker", spawn = "ch_prop_ch_fib_01a" },
	}},

	{categoryName = "Medical", description = "Props and objects used for medical roleplay", components = {
		{name = "ALS Bag", spawn = "xm_prop_x17_bag_med_01a" },
		{name = "First Aid Kit", spawn = "v_ret_ta_firstaid" },
		{name = "ECG Machine", spawn = "prop_ecg_01" },
		{name = "AED", spawn = "prop_idol_case_02" },
		{name = "Water Fire Extinguisher", spawn = "prop_fire_exting_1a" },
		{name = "CO2 Fire Extinguisher", spawn = "prop_fire_exting_1b" },
		{name = "Body Bag", spawn = "xm_prop_body_bag" },
	}},

	{categoryName = "Miscellaneous", description = "Props and objects which don\'t fit into above categories", components = {
    	{name = "Scene Lights", spawn = "prop_worklight_03b" },
    	{name = "Gazebo", spawn = "prop_gazebo_02" },
    	{name = "Foldable Table", spawn = "bkr_prop_weed_table_01b"},
    	{name = "Portable Generator", spawn = "prop_generator_01a"},
		{name = "Construction Saw", spawn = "prop_tool_consaw"},
		{name = "Vertical Ladder", spawn = "prop_byard_ladder01"},
		{name = "Vertical Plank", spawn = "prop_cons_plank"},
		{name = "Horizontal Plank", spawn = "frag_plank_d"},

		{name = "Portable Radio", spawn = "prop_radio_01"},
		{name = "Laptop", spawn = "prop_laptop_lester2"},
	}},
}